apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reservationstore
spec:
  type: state.azure.cosmosdb
  version: v1
  metadata:
  - name: url
    value: # replace
  - name: masterKey
    value: # replace
  - name: database
    value: state
  - name: collection
    value: reservationstate