@baseUrl = localhost
@orderservicePort = 5001
@orderserviceDaprPort = 5010
###
# @name simpleOrderRequest
POST http://{{baseUrl}}:{{orderserviceDaprPort}}/v1.0/invoke/order-service/method/order HTTP/1.1
content-type: application/json

{
  "CustomerCode": "Davide",
  "Date": "{{$datetime 'YYYY-MM-DD'}}",
  "Items": [
    {
      "ProductCode": "rockiecookie",
      "Quantity": {{$randomInt 2 8}}
    },
    {
      "ProductCode": "bussola{{$randomInt 1 100}}",
      "Quantity": {{$randomInt 1 8}}
    }
  ],
  "SpecialRequests" : [
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "rockiecookie",
        "Quantity": 2
      }
    }
  ]
}
###
@orderId = {{simpleOrderRequest.response.body.$}}
# get order from ASP.NET endpoint
GET http://{{baseUrl}}:{{orderservicePort}}/order/{{orderId}}
###
# get order from Dapr endpoint invoking service
GET http://{{baseUrl}}:{{orderserviceDaprPort}}/v1.0/invoke/order-service/method/order/{{orderId}} 
###
# @name erraticOrderRequest
POST http://{{baseUrl}}:{{orderserviceDaprPort}}/v1.0/invoke/order-service/method/order HTTP/1.1
content-type: application/json

{
  "CustomerCode": "Davide",
  "Date": "{{$datetime 'YYYY-MM-DD'}}",
  "Items": [
    {
      "ProductCode": "rockiecookie",
      "Quantity": {{$randomInt 2 8}}
    },
    {
      "ProductCode": "bussola8",
      "Quantity": {{$randomInt 1 8}}
    },
    {
      "ProductCode": "crazycookie",
      "Quantity": 2
    }
  ],
  "SpecialRequests" : [
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "crazycookie",
        "Quantity": 1
      }
    },
    {
      "CustomizationId" : "08ffffcc-7591-4702-ffff-fff6787bfffe",
      "Scope": 
      {
        "ProductCode": "rockiecookie",
        "Quantity": 2
      }
    }
  ]
}
###
@erraticOrderId = {{erraticOrderRequest.response.body.$}}
# get order from ASP.NET endpoint
GET http://{{baseUrl}}:{{orderservicePort}}/order/{{erraticOrderId}}
###
# get order from Dapr endpoint invoking service
GET http://{{baseUrl}}:{{orderserviceDaprPort}}/v1.0/invoke/order-service/method/order/{{erraticOrderId}} 
###
# get order from Dapr endpoint retrieving state 
GET http://{{baseUrl}}:{{orderserviceDaprPort}}/v1.0/state/orderstore/{{erraticOrderId}}
###
@reservationservicePort = 5002
@reservationactorserviceDaprPort = 5014
###
GET http://{{baseUrl}}:{{reservationactorserviceDaprPort}}/v1.0/actors/ReservationItemActor/rockiecookie/state/reservationitem
###
GET http://{{baseUrl}}:{{reservationactorserviceDaprPort}}/v1.0/actors/ReservationItemActor/rockiecookie/method/GetBalance
###
GET http://{{baseUrl}}:{{reservationservicePort}}/balance/rockiecookie