apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: commonpubsub
  namespace: default
spec:
  type: pubsub.azure.servicebus
  version: v1
  metadata:
  - name: connectionString
    value: # Replace
  - name: lockDurationInSec
    value: 60
  - name: lockRenewalInSec
    value: 30